services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app/api:Z
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - agentdemo

  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    networks:
      - agentdemo
  
  jaeger:
    image: jaegertracing/all-in-one
    ports:
        - 4318
        - 16686:16686
    environment:
        COLLECTOR_OTLP_ENABLED: true
    networks:
      - agentdemo

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    networks:
      - agentdemo

  collector:
    image: otel/opentelemetry-collector-contrib
    volumes: 
      - ./collector/collector.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "8889:8889"
    networks:
      - agentdemo

networks:
  agentdemo:
